# Generated by Django 3.2 on 2021-08-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'architecture',
            },
        ),
        migrations.CreateModel(
            name='DesktopInterface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'desktopInterface',
            },
        ),
        migrations.CreateModel(
            name='Distro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('os_type', models.CharField(blank=True, choices=[('LINUX', 'LINUX'), ('BSD', 'BSD'), ('SOLARIS', 'SOLARIS'), ('OTHER_OS', 'OTHER_OS')], default='Linux', max_length=8, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('based_on', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('DESKTOP', 'DESKTOP'), ('LIVE_MEDIUM', 'LIVE_MEDIUM'), ('RASPBERRY_PI', 'RASPBERRY_PI'), ('FROM_RAM', 'FROM_RAM')], max_length=12, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('DORMANT', 'DORMANT'), ('DISCONTINUED', 'DISCONTINUED')], max_length=12, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('home_page', models.CharField(blank=True, max_length=255, null=True)),
                ('user_forums', models.CharField(blank=True, max_length=255, null=True)),
                ('architectures', models.ManyToManyField(blank=True, db_table='distro_architecture', related_name='distros', to='distrowatch_api.Architecture')),
                ('desktop_interfaces', models.ManyToManyField(blank=True, db_table='distro_desktop_interface', related_name='distros', to='distrowatch_api.DesktopInterface')),
            ],
            options={
                'db_table': 'distro',
            },
        ),
    ]
